Fix compiler error in Unity 2020 -> StreamApiException.cs(121,67): error CS1503: Argument 1: cannot convert from
'IReadOnlyDictionary<string, string>' to 'IDictionary<string, string>'